<?php 
	print '
	<h1>O nama</h1>
	<h2>Slavljenički povratak Vatrenih 2018.</h2>
	<video width="50%" controls poster="img/repka2.jpg" >
	  <source src="video/repka.mp4" type="video/mp4">
	  Your browser does not support HTML5 video.
	</video>
	<p>Hrvatski nogometni savez osnovan je 13. lipnja 1912. godine. HNS je član Fife od 1941. godine, a članstvo je potvrđeno 3. srpnja 1992., nakon što je Hrvatska postala samostalna. HNS je primljen u punopravno članstvo Uefe 17. lipnja 1993. godine.</p>
	<p>Izborom dr. Milovana Zoričića za šefa nogometne sekcije Hrvatskog športskog saveza, 13. lipnja 1912. godine, službeno je započela bogata povijest Hrvatskog nogometnog saveza.</p>
	<p>Njegov zamjenik bio je Zvonimir Klobučar, a Ivan Pipinić je bio rizničar. Oni su, zajedno s Hinkom Würthom, Dragutinom Albrechtom i Brankom Gavellom, preuzeli obvezu razvoja i unapređenja nogometa u Hrvatskoj pa se stoga s pravom mogu smatrati prvim članovima nacionalne nogometne organizacije.</p>
	<p>Nogomet su u današnjem obliku prvobitno u Hrvatskoj igrali još 1873. godine Englezi koji su došli u Rijeku radi izgradnje tvornice, a 1880. godine lokalni hrvatski mladići počeli su igrati nogomet u Županji. Nogometna lopta s kojom su se igrale utakmice 1880. godine i kasnije na području Županje sačuvana je i danas. Postoje i zapisi o tome kako su nogomet igrali učenici u Zadru, te nešto kasnije (oko 1900. godine) u Istri, Slavoniji i drugim gradovima širom Hrvatske.</p>
	<pPrvo izdanje Pravila igre na hrvatskom jeziku tiskano je 1896. godine u Zagrebu. Na početku se nogomet igrao u okviru gimnastičke organizacije Hrvatski sokol. Prvi hrvatski sportski klub koji u svom imenu naglašava opredijeljenost za nogomet je Prvi nogometni i športski klub (PNIŠK) Zagreb, osnovan 1903. godine.</p>
	<p>Početkom 20. stoljeća, kada su u Hrvatskoj počeli nastajati i drugi nogometni klubovi, došlo je do želje nogometnih čelnika za formiranjem nacionalnog nogometnog saveza. Težnja Hrvata za uspostavljanjem vlastitog sportskog saveza još je više rasla nakon što je u Zagrebu, na Marulićevom trgu, na mjestu na kojem se danas nalazi Sveučilišna biblioteka, 28. listopada 1906. odigrana prva javna nogometna utakmica između HAŠK-a i PNIŠK-a (1:1).</p>
	<pReprezentacija Hrvatske odigrala je prve javne međunarodne utakmice u Pragu 23. i 26. lipnja 1907. protiv Slavije, u to vrijeme jedne od najboljih nogometnih momčadi Češke i Europe.</p>
	<p>Djelovanje Hrvatskog nogometnog saveza poslije Prvog svjetskog rata moralo je biti prilagođeno političkim okolnostima, a nakon Drugog svjetskog rata nastavljena je borba za postizanje jednakosti unutar jugoslavenske nogometne organizacije. U tom su razdoblju predsjednici bili Mišo Hršak, Ratko Vilinčić, Lazo Vračarić, Boris Bakrac, Vlado Ranogajec, Mirko Oklobdžija i Pero Splivalo. Uspostavljanjem suverene, nezavisne i demokratske Hrvatske nakon izbora 1990. godine obilježen je početak izrazito uspješne ere.</p>
	<p>Naime, hrvatska je reprezentacija u tom razdoblju izborila plasman na 11 od 13 velikih natjecanja, propustivši tek EP 2000. i SP 2010. godine. Do 2018. godine, kruna tih nastupa bilo je osvajanje svjetske bronce u Francuskoj 1998. godine, kada su Vatreni na svojoj prvoj svjetskoj smotri zadivili svijet, a aktualni predsjednik HNS-a Davor Šuker bio je prvi strijelac natjecanja sa šest pogodaka. Na Svjetskom prvenstvu u Rusiji 2018. godine, generacija predvođena izbornikom Zlatkom Dalićem uspjela je nadmašiti legendarne brončane te izboriti finale Svjetskog prvenstva u kojem je s 4:2 izgubila od Francuske. Srebrne Vatrene u Zagrebu je dočekalo više od pola milijuna razdraganih navijača, nakon što su svojim nastupima u Rusiji razgalili srca cijele nacije. Nakon serije briljantnih predstava, kapetan Luka Modrić proglašen je najboljim igračem turnira za što je dobio Zlatnu loptu.
	Na prvom velikom natjecanju, Europskom prvenstvu 1996. godine u Engleskoj, Hrvatska je stigla do četvrtfinala i ispala od kasnijeg prvaka Njemačke, a korak do polufinala ostala je i 2008. godine na europskoj smotri u Austriji i Švicarskoj.</p>
	<p>Uz uspjehe seniorske nacionalne selekcije, Hrvatski nogometni savez ponosan je i na rad s mlađim kategorijama te brojne nastupe mladih Vatrenih na završnim turnirima Europskog i Svjetskog prvenstva, a posebnog se organizacijskog izazova prihvatio i u svibnju 2017. godine, kao vrlo uspješan domaćin Europskog prvenstva za igrače do 17 godina.
	Generacija velikana sa Šukerom, Bobanom, Prosinečkim, Bilićem i ostalima pod vodstvom izbornika Blaževića utrla je put svojim nasljednicima, koji su pruženu priliku maksimalno iskoristili te ostavili dubok trag i u najvećim svjetskim klubovima. Sadašnji kapetan Hrvatske Modrić već je četiri puta osvajao Ligu prvaka s Real Madridom, dok se Mandžukić dva puta upisivao u strijelce u finalima, s Bayernom i Juventusom.
	Imena poput rekordera po broju nastupa i bivšeg kapetana Srne, zatim Rakitića, Prše, braće Kovač, Olića i drugih ostaju među najboljim ambasadorima Hrvatske u svijetu te neizbrisiva potvrda kvalitetnog rada Hrvatskog nogometnog saveza.</p>';
?>